### ISSUE TITLE
implement a proper minimax algorithm

### ISSUE THREAD

**Issue by dfirebaugh** [dfirebaugh/tic-tac-py#2]

**Comment by Peradon** [comment]
Let me see what I can help!

**Comment by Samalot** [comment]
im on giving it a shot too :)

**Comment by zeddmaxx** [comment]
@dfirebaugh Hey, can I work on this ?

**Comment by dfirebaugh** [comment]
@Samalot already submitted a great PR.  Feel free to submit your own on a separate branch.  

Thanks,
DF
